# TCL File Generated by Component Editor 18.1
# Sat Dec 02 00:17:56 EST 2023
# DO NOT MODIFY


# 
# sdram_interface "SDRAM Avalon MM Master" v1.1
# Joe Dai 2023.12.02.00:17:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sdram_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME sdram_interface
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Joe Dai"
set_module_property DISPLAY_NAME "SDRAM Avalon MM Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sdram_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sdram_interface.sv SYSTEM_VERILOG PATH sdram_interface.sv TOP_LEVEL_FILE
add_fileset_file write_master.v VERILOG PATH write_master.v
add_fileset_file latency_aware_read_master.v VERILOG PATH latency_aware_read_master.v


# 
# parameters
# 
add_parameter BASE_ADDR_OFFSET INTEGER 0 ""
set_parameter_property BASE_ADDR_OFFSET DEFAULT_VALUE 0
set_parameter_property BASE_ADDR_OFFSET DISPLAY_NAME BASE_ADDR_OFFSET
set_parameter_property BASE_ADDR_OFFSET WIDTH ""
set_parameter_property BASE_ADDR_OFFSET TYPE INTEGER
set_parameter_property BASE_ADDR_OFFSET UNITS None
set_parameter_property BASE_ADDR_OFFSET ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BASE_ADDR_OFFSET DESCRIPTION ""
set_parameter_property BASE_ADDR_OFFSET HDL_PARAMETER true
add_parameter COLOR_WIDTH INTEGER 32 ""
set_parameter_property COLOR_WIDTH DEFAULT_VALUE 32
set_parameter_property COLOR_WIDTH DISPLAY_NAME COLOR_WIDTH
set_parameter_property COLOR_WIDTH WIDTH ""
set_parameter_property COLOR_WIDTH TYPE INTEGER
set_parameter_property COLOR_WIDTH ENABLED false
set_parameter_property COLOR_WIDTH UNITS None
set_parameter_property COLOR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLOR_WIDTH DESCRIPTION ""
set_parameter_property COLOR_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH INTEGER 32 ""
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 32
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH WIDTH ""
set_parameter_property FIFO_DEPTH TYPE INTEGER
set_parameter_property FIFO_DEPTH ENABLED false
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIFO_DEPTH DESCRIPTION ""
set_parameter_property FIFO_DEPTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32 ""
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH WIDTH ""
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH ENABLED false
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH DESCRIPTION ""
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter COORD_WIDTH INTEGER 16 ""
set_parameter_property COORD_WIDTH DEFAULT_VALUE 16
set_parameter_property COORD_WIDTH DISPLAY_NAME COORD_WIDTH
set_parameter_property COORD_WIDTH WIDTH ""
set_parameter_property COORD_WIDTH TYPE INTEGER
set_parameter_property COORD_WIDTH ENABLED false
set_parameter_property COORD_WIDTH UNITS None
set_parameter_property COORD_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COORD_WIDTH DESCRIPTION ""
set_parameter_property COORD_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point rm
# 
add_interface rm avalon start
set_interface_property rm addressUnits SYMBOLS
set_interface_property rm associatedClock clock
set_interface_property rm associatedReset reset
set_interface_property rm bitsPerSymbol 8
set_interface_property rm burstOnBurstBoundariesOnly false
set_interface_property rm burstcountUnits WORDS
set_interface_property rm doStreamReads false
set_interface_property rm doStreamWrites false
set_interface_property rm holdTime 0
set_interface_property rm linewrapBursts false
set_interface_property rm maximumPendingReadTransactions 0
set_interface_property rm maximumPendingWriteTransactions 0
set_interface_property rm readLatency 0
set_interface_property rm readWaitTime 1
set_interface_property rm setupTime 0
set_interface_property rm timingUnits Cycles
set_interface_property rm writeWaitTime 0
set_interface_property rm ENABLED true
set_interface_property rm EXPORT_OF ""
set_interface_property rm PORT_NAME_MAP ""
set_interface_property rm CMSIS_SVD_VARIABLES ""
set_interface_property rm SVD_ADDRESS_GROUP ""

add_interface_port rm rm_address address Output ADDR_WIDTH
add_interface_port rm rm_readdata readdata Input COLOR_WIDTH
add_interface_port rm rm_read read Output 1
add_interface_port rm rm_readdatavalid readdatavalid Input 1
add_interface_port rm rm_waitrequest waitrequest Input 1
add_interface_port rm rm_byteenable byteenable Output 4


# 
# connection point wm
# 
add_interface wm avalon start
set_interface_property wm addressUnits SYMBOLS
set_interface_property wm associatedClock clock
set_interface_property wm associatedReset reset
set_interface_property wm bitsPerSymbol 8
set_interface_property wm burstOnBurstBoundariesOnly false
set_interface_property wm burstcountUnits WORDS
set_interface_property wm doStreamReads false
set_interface_property wm doStreamWrites false
set_interface_property wm holdTime 0
set_interface_property wm linewrapBursts false
set_interface_property wm maximumPendingReadTransactions 0
set_interface_property wm maximumPendingWriteTransactions 0
set_interface_property wm readLatency 0
set_interface_property wm readWaitTime 1
set_interface_property wm setupTime 0
set_interface_property wm timingUnits Cycles
set_interface_property wm writeWaitTime 0
set_interface_property wm ENABLED true
set_interface_property wm EXPORT_OF ""
set_interface_property wm PORT_NAME_MAP ""
set_interface_property wm CMSIS_SVD_VARIABLES ""
set_interface_property wm SVD_ADDRESS_GROUP ""

add_interface_port wm wm_address address Output ADDR_WIDTH
add_interface_port wm wm_writedata writedata Output COLOR_WIDTH
add_interface_port wm wm_write write Output 1
add_interface_port wm wm_waitrequest waitrequest Input 1
add_interface_port wm wm_byteenable byteenable Output 4


# 
# connection point ext_interface
# 
add_interface ext_interface conduit end
set_interface_property ext_interface associatedClock clock
set_interface_property ext_interface associatedReset ""
set_interface_property ext_interface ENABLED true
set_interface_property ext_interface EXPORT_OF ""
set_interface_property ext_interface PORT_NAME_MAP ""
set_interface_property ext_interface CMSIS_SVD_VARIABLES ""
set_interface_property ext_interface SVD_ADDRESS_GROUP ""

add_interface_port ext_interface start start Input 1
add_interface_port ext_interface done done Output 1
add_interface_port ext_interface x_start x_start Input COORD_WIDTH
add_interface_port ext_interface x_length x_length Input COORD_WIDTH
add_interface_port ext_interface y_start y_start Input COORD_WIDTH
add_interface_port ext_interface y_length y_length Input COORD_WIDTH
add_interface_port ext_interface current_x current_x Output COORD_WIDTH
add_interface_port ext_interface current_y current_y Output COORD_WIDTH
add_interface_port ext_interface old_color old_color Output COLOR_WIDTH
add_interface_port ext_interface new_color new_color Input COLOR_WIDTH

